### ISSUE TITLE
SUSE download links missing

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla.com#43]
See https://qupzilla.com/download#suse

**Comment by cranes-bill** [comment]
Too much [Open suse](https://ftp.gwdg.de/pub/opensuse/repositories/KDE%3A/Extra/)s :smile: 
Only **Tumbleweed** has latest QupZilla

**Comment by Martii** [comment]
One would be nice on the site... picking the latest stable would be nice.

**Comment by javierllorente** [comment]
The link was using http. I have just updated it. 
Commit 3b569968e056e5e8abb8a1a5148207f3b2c85b70

**Comment by javierllorente** [comment]
@nowrep could you please deploy it? Thanks

**Comment by Martii** [comment]
That would help.... thanks. :)

**Comment by nowrep** [comment]
Done

**Comment by Martii** [comment]
@nowrep 
Upon further looking into this it's still partially there. The fix did make it so that the green buttons showed up as such:


<img src="https://cloud.githubusercontent.com/assets/114709/24079048/4ecb10d8-0c44-11e7-8b6d-d8769b166289.png" alt="http instead of https" title="Click to enlarge" width="103" height="75" />


... however you may notice the status bar in QupZilla is still `http` only with hovering over the buttons.

Randomly tested click with console message of:

``` sh-session
js: Mixed Content: The page at 'https://www.qupzilla.com/download#suse' was loaded over HTTPS, but requested an insecure resource 'http://software.opensuse.org/ymp/KDE:Extra/openSUSE_Leap_42.1/qupzilla.ymp'. This request has been blocked; the content must be served over HTTPS.
```

I understand it's **over on another domain** but it could confuse first time installers that are green button oriented.

Thanks for the relook.

Using QupZilla 2.1.2 current HEAD built on ROSA. :)
