### ISSUE TITLE
qupzilla.com super slow

### ISSUE THREAD

**Issue by Martii** [QupZilla/qupzilla.com#46]
Trying to get the AppImage *(and tested Windows download as well which took about an hour to get)*... it seems the server is a wee bit slow today.

``` sh-session
$ wget https://qupzilla.com/uploads/QupZilla-2.1.2.AppImage
--2017-08-02 16:00:29--  https://qupzilla.com/uploads/QupZilla-2.1.2.AppImage
Resolving qupzilla.com (qupzilla.com)... 46.36.35.106
Connecting to qupzilla.com (qupzilla.com)|46.36.35.106|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84088856 (80M)
Saving to: ‘QupZilla-2.1.2.AppImage’

QupZilla-2.1.2.AppImage        3%[=>                                                                ] 2.87M 16.9KB/s        eta 80m 1s
```

``` sh-session
$ ping qupzilla.com
PING qupzilla.com (46.36.35.106) 56(84) bytes of data.
64 bytes from 106-35.hukot.net (46.36.35.106): icmp_req=1 ttl=51 time=177 ms
64 bytes from 106-35.hukot.net (46.36.35.106): icmp_req=2 ttl=51 time=178 ms
64 bytes from 106-35.hukot.net (46.36.35.106): icmp_req=3 ttl=51 time=178 ms
```
Seems to start lagging on telia.net with a `$ traceroute qupzilla.com`.

This may be related to QupZilla/qupzilla#2401

**Comment by Martii** [comment]
Completed AppImage download with post session of:

``` sh-session
QupZilla-2.1.2.AppImage                    100%[=====================================================================================>]  80.19M  17.3KB/s    in 81m 40s 

2017-08-02 17:22:11 (16.8 KB/s) - ‘QupZilla-2.1.2.AppImage’ saved [84088856/84088856]
```

**Comment by nowrep** [comment]
Well, 177ms is not really bad ping considering the server is in Czech Republic and you in USA.

Anyway, occasional server issues are to be expected, I guess...

**Comment by Martii** [comment]
This is better today...

``` sh-session
QupZilla-2.1.2.AppImage                15%[=========>                                                             ]  12.29M   577KB/s    eta 2m 4s  ^
```

telia.net must have fixed their lag or the server was reset/updated because an ~80 *(yes that's eighty minutes)* minute download isn't  just lag it's a problem that should always be addressed. :)

**Comment by nowrep** [comment]
I restarted the server around the time I wrote the last comment.
Your current speed looks fine considering the server location.

**Comment by Martii** [comment]
@nowrep 
This seems to be back again. Estimate to download is > ~72 minutes.
