### ISSUE TITLE
Falkon successor of QupZilla, status of this project?

### ISSUE THREAD

**Issue by probonopd** [QupZilla/qupzilla.com#48]
Is KDE Falkon a successor of QupZilla, and what does this mean for the current status of this project?

**Comment by nowrep** [comment]
It's just a name change more or less + move to KDE infrastructure. There is no change in project direction (and also no KDE hard dependencies will be done and Windows will still be supported).

**Comment by probonopd** [comment]
Thanks for the clarification. Will it still be possible to use GitHub Issues?

**Comment by nowrep** [comment]
No, https://bugs.kde.org will be used instead.

**Comment by probonopd** [comment]
This means it will be much harder to submit issues or make small (drive-by) contributions, e.g., fixing typos and such, which so far could be done using the GitHub web interface. Hiding the source code in a non-Github system (which does not show up in GitHub full text searches either) means additional barriers to participate. Hopefully it's worth the tradeoff.
